services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/tinyurl
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis

  worker:
    build: .
    command: npm run worker
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/tinyurl
    depends_on:
      - mongo

volumes:
  mongo_data:
